### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [xpengy/nd#1]
is there any update?

**Comment by YukinoshitaYukino123** [comment]
how to use this program?

**Comment by xpengy** [comment]
1. install python
2. create folder and put nd.py and requirements.txt there
3. open terminal (powershell/cmd) -> go to folder -> pip install -r requirements.txt

at the very bottom you will have this code.

```
nd = NovelpiaDownloader()
nd.login("test@email.com", "password123")
```

`nd.download_all(NOVEL_ID)` or `nd.download(VIEWER_ID)`

so your finishing code will be something like 

```
nd = NovelpiaDownloader()
nd.login("test@email.com", "password123")
nd.download_all(174152)
```

once you have done that, save (ctrl+s).

then go to your terminal and run `py nd.py`

it will show up in a folder called output in the same folder nd.py is in. chapters are not a continuous text file, they are separated.  also, it will break if you don't have 19+, but there are 19+ chapters inside.

**Comment by YukinoshitaYukino123** [comment]
thanks, i am now able to run the program, also can i start scraping from a specific chapter eg: start from chapter 50 to the end?

**Comment by xpengy** [comment]
i will try to add that feature later today or tomorrow

**Comment by YukinoshitaYukino123** [comment]
Thanks for the feature addition, and also while on it can you also add a translation feature using google tl? So the output file is also translated, once again thanks

**Comment by xpengy** [comment]
i can’t do that. 
google cloud translation requires payment, and py-googletrans breaks a lot.
