### ISSUE TITLE
Folder naming issue

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [xpengy/nd#2]
Unable to scrap novel if the title has the following special characters like \ / : * ? " < > | 
novel id example (87304)

**Comment by YukinoshitaYukino123** [comment]
Also, is it possible to add chapter number and title in the inside of the text file and merge them together?

**Comment by xpengy** [comment]
ill fix the first one in a bit.
ill try to do the second one as well, been busy recently but ill try to do them by sunday
