### ISSUE TITLE
Skip chapter problem 

### ISSUE THREAD

**Issue by YukinoshitaYukino123** [xpengy/nd#3]
![image](https://github.com/xpengy/nd/assets/128869659/41647906-53af-4ca5-b3df-fade0a3ab6c8)
![image](https://github.com/xpengy/nd/assets/128869659/73edd38e-f17d-4788-b365-23d969501f7a)
unable to download start download from a specific chapter

**Comment by xpengy** [comment]
should work now, reopen if doesnt

**Comment by YukinoshitaYukino123** [comment]
Hi, kinda oot but I was wondering are you able to fix this code to scrap
the novel information? I got this code from my friend but I don't know why
it's not working

import requests_html
from bs4 import BeautifulSoup
from requests_html import HTMLSession
from googletrans import Translator
from functools import reduce
from requests_html import AsyncHTMLSession

def translate(novel_id):
  URL = "https://novelpia.com/novel/" + str(novel_id)
  session = HTMLSession()
  translator = Translator()
  r = session.get(URL)
  soup = BeautifulSoup(r.text,'html.parser')
  kr_name = "KR Name: " + (soup.select_one('div
[style="font-weight:700;font-size:15px;margin-bottom:5px;"]').text)
  name = "__" + translator.translate(kr_name).text + "__"
  summary =
soup.select_one('span[style="font-weight:300;font-size:12px;word-break:
break-word;"]').text
  summary = translator.translate(summary).text
  tags = soup.select('span[style="color:#5032df;user-select:
none;cursor:pointer;"]')
  tags = list(map(lambda x: translator.translate(x.text).text, tags))
  tags = '`Tags: ' + ', '.join(tags) + "`"
  android = " [Android: use Lithium, MoonReader] \n [IOS: use iBooks,
Calibro, Documents, Kybooks 3, Pocketbook] \n [PC: use SumatraPDF, Calibre]"
  print(name)
  print(kr_name)
  print("Novel ID: " + str(novel_id))
  print("```" + summary + "```")
  print(tags)
  print("```CSS\n" + android + "\n ```")

#INSERT NOVEL NUMBER translate(199786)

thanks

Pada tanggal Sen, 5 Jun 2023 pukul 03.08 pengy ***@***.***>
menulis:
